# Generated by Django 5.0.1 on 2024-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_user_created_at_user_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_done',
            field=models.BooleanField(default=False),
        ),
    ]
