# Generated by Django 5.0.1 on 2024-12-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0007_otprecord_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
