# Generated by Django 5.0.1 on 2024-12-23 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0008_user_wallet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCompanyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('trade_performed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
