# Generated by Django 5.0.1 on 2025-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_payment_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
