# Generated by Django 5.0.1 on 2025-02-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0012_user_payment_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_payment_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
