# Generated by Django 5.0.1 on 2024-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribermapping',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
