# Generated by Django 5.0.1 on 2024-09-28 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscriptionplan_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('investment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('investment_active', models.BooleanField(default=True)),
                ('added_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentsMapping',
            fields=[
                ('investment_mapping', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment_amount', models.FloatField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='core.investments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
