# Generated by Django 5.0.1 on 2024-09-28 10:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investments_investmentsmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='bought_at',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investments',
            name='investment_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InvestmentSquared',
            fields=[
                ('investment_squared_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment_amount', models.FloatField()),
                ('bought_at', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sold_at', models.FloatField()),
                ('sold_on', models.DateField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments_sold', to='core.investments')),
            ],
        ),
    ]
