# Generated by Django 5.0.1 on 2024-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_investments_bought_at_investments_investment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='bought_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
