# Generated by Django 5.0.1 on 2024-09-30 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_investments_created_at_investments_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentsmapping',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investmentsquared',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investmentsmapping',
            name='user',
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('portfolio_mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_subscription', to='core.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Investments',
        ),
        migrations.DeleteModel(
            name='InvestmentSquared',
        ),
        migrations.DeleteModel(
            name='InvestmentsMapping',
        ),
    ]
