# Generated by Django 5.0.1 on 2024-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscriptionplan_re_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribermapping',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscribermapping',
            name='withdraw_request_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscribermapping',
            name='withdraw_request_raised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscribermapping',
            name='withdraw_request_raised_accepted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscribermapping',
            name='withdraw_request_raised_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
