# Generated by Django 5.0.1 on 2024-10-13 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usersubscribermapping_paid_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='amount_added_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
