# Generated by Django 5.0.1 on 2024-10-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userportfolio_amount_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribermapping',
            name='last_payout_done',
            field=models.DateField(blank=True, null=True),
        ),
    ]
