# Generated by Django 5.0.1 on 2024-10-13 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usersubscribermapping_last_payout_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayouts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('user_payouts_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_amount', models.IntegerField()),
                ('user_subs_map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sub_payout', to='core.usersubscribermapping')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
