# Generated by Django 5.0.1 on 2024-10-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userpayouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayouts',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
