# Generated by Django 5.0.1 on 2024-10-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userpayouts_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayouts',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
