# Generated by Django 5.0.1 on 2024-10-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userpayouts_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribermapping',
            name='next_payment_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
