# Generated by Django 5.0.1 on 2024-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_userpayouts_unique_together_referralpayouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpayouts',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
