# Generated by Django 5.0.1 on 2024-12-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_referralpayouts_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='sub_icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usersubscribermapping',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
