# Generated by Django 5.0.1 on 2024-12-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_subscriptionplan_sub_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority',
            field=models.IntegerField(default=2),
        ),
    ]
