# Generated by Django 5.0.1 on 2024-12-25 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_subscriptionplan_is_active_subscriptionplan_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSubscriptionBackground',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
