# Generated by Django 5.0.1 on 2025-01-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_addsubscriptionbackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribermapping',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
