# Generated by Django 5.0.1 on 2025-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_usersubscribermapping_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_exclusive',
            field=models.BooleanField(default=True),
        ),
    ]
