# Generated by Django 5.0.1 on 2025-01-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_subscriptionplan_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribermapping',
            name='withdrawal_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
