# Generated by Django 5.0.1 on 2025-01-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_usersubscribermapping_withdrawal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribermapping',
            name='amount_activation_pending',
            field=models.FloatField(default=0.0),
        ),
    ]
