# Generated by Django 5.0.1 on 2025-01-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_usersubscribermapping_amount_activation_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribermapping',
            name='wallet_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
