# Generated by Django 5.0.1 on 2025-02-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_usersubscribermapping_wallet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trending_symbols',
            },
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
