# Generated by Django 5.0.1 on 2025-02-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_trendingsymbol_alter_subscriptionplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='expected_return',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.FloatField(),
        ),
    ]
