# Generated by Django 5.0.1 on 2025-02-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_subscriptionplan_expected_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayouts',
            name='payout_amount',
            field=models.FloatField(),
        ),
    ]
