# Generated by Django 5.0.1 on 2025-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_userpayouts_payout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='amount',
            field=models.FloatField(),
        ),
    ]
