"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import datetime
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from utility.env_setup import environment

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)n-9096sh)l3crl-ssb58korw(x(#t221s^!_(sq%u71gqs4ro'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['api.tradestreaks.lol','localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django_celery_results',
    'corsheaders',
    'django_rest_passwordreset',
    'oauth2_provider',
    'rest_framework',
    'core',
    'e_commerce',

]

MIDDLEWARE = [
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'
AUTH_USER_MODEL = 'e_commerce.User'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': environment.DJANGO_POSTGRES_DATABASE,
        'USER': environment.DJANGO_POSTGRES_USER,
        'PASSWORD': environment.DJANGO_POSTGRES_PASSWORD,
        'HOST': environment.DJANGO_POSTGRES_HOST,
        'PORT': environment.DJANGO_POSTGRES_PORT,
    },
}


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# AWS_ACCESS_KEY_ID = environment.AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY = environment.AWS_SECRET_ACCESS_KEY
# AWS_STORAGE_BUCKET_NAME = environment.AWS_STORAGE_BUCKET_NAME
# AWS_S3_ENDPOINT_URL = environment.AWS_S3_ENDPOINT_URL
# AWS_S3_REGION_NAME='blr1'
# AWS_S3_OBJECT_PARAMETERS = {
#     'CacheControl': 'max-age=86400',
#     "ACL": "public-read",
# }
# AWS_LOCATION= environment.AWS_LOCATION
# AWS_QUERYSTRING_AUTH = False

# Static files (CSS, JavaScript, images)

#MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/blogsmedia/blogsmedia/blogsmedia/media/'



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# #MEDIA_URL = 'https://%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_LOCATION)
# #STATICFILES_STORAGE = 'ecommerce.storage_backends.StaticRootS3Storage'

CORS_ORIGIN_ALLOW_ALL =True
# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:3001',
#     'http://localhost:3000',
#     'http://localhost:4000',
#     'https://kothaiimpex.com',
#     'http://127.0.0.1:5500'
# )

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_ALL_ORIGINS=True
CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)
CSRF_TRUSTED_ORIGINS = ['https://*.tradestreaks.lol']
CELERY_BROKER_URL = 'redis://tradestreak_redis:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TIMEZONE = 'Asia/Kolkata'


EMAIL_BACKEND = environment.EMAIL_BACKEND
EMAIL_HOST =environment.EMAIL_HOST
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER =environment.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD =environment.EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL =environment.DEFAULT_FROM_EMAIL
